### ISSUE TITLE
CLI 에서 `korpora fetch --corpus all` 실행 시 fetch 기능이 제공되지 않은 말뭉치에 의하여 오류가 발생합니다.

### ISSUE THREAD

**Issue by lovit** [ko-nlp/Korpora#170]
아래의 오류를 해결하기 위해서는 fetch 함수가 제공되지 않는 말뭉치는 fetch all 에서 skip 하는 기능을 추가해야 합니다.

(terminal)
```
$ korpora fetch
## Arguments of Korpora CLI ##
  - corpus : all
  - force_download : False
  - func : fetch
  - root : None
Traceback (most recent call last):
  File "~/venv3.6.9/bin/korpora", line 33, in <module>
    sys.exit(load_entry_point('Korpora==0.1.0', 'console_scripts', 'korpora')())
  File "~/venv3.6.9/lib/python3.6/site-packages/Korpora-0.1.0-py3.6.egg/Korpora/cli.py", line 64, in main
  File "~/venv3.6.9/lib/python3.6/site-packages/Korpora-0.1.0-py3.6.egg/Korpora/task_fetch.py", line 7, in fetch
  File "~/venv3.6.9/lib/python3.6/site-packages/Korpora-0.1.0-py3.6.egg/Korpora/loader.py", line 67, in fetch
  File "~/venv3.6.9/lib/python3.6/site-packages/Korpora-0.1.0-py3.6.egg/Korpora/korpus_aihub_translation.py", line 134, in fetch_aihub
NotImplementedError: https://www.aihub.or.kr/ 에서 개별 신청 후 직접 데이터를 받으셔야 합니다.
이에 따라 AI Hub 의 말뭉치는 fetch 기능을 제공하지 않습니다
```

**Comment by lovit** [comment]
Resolved
